### ISSUE TITLE
softlock issue

### ISSUE THREAD

**Issue by Azuryte55** [EtherealEmil/UsualScrap#47] opened 2024-10-23 00:18 UTC
when i take the radioactive cell sometime the game will not take the item and we cant do anything except closing the game (it happened more when you launch the save file multiple times without playing)

**Comment by EtherealEmil** [comment] 2024-10-23 01:56
Are you picking it up in orbit and do you have other mods installed? I've not experienced this or seen this issue yet.

**Comment by Azuryte55** [comment] 2024-11-02 18:38
> What version of the mod are you using, what game version are you on, are you picking it up in orbit, are there any errors in the console, and do you have other mods installed? I've not experienced this or seen this issue yet.

sorry to respond very late but i can send you my modpack it's a bit huge but i checked for 3hours to see if everything works (the only issue are the fps drop too 90fps to 25fps and the softlock) it does this only on your radioactive cell so i dont know...

**Comment by Azuryte55** [comment] 2024-11-02 18:40
> What version of the mod are you using, what game version are you on, are you picking it up in orbit, are there any errors in the console, and do you have other mods installed? I've not experienced this or seen this issue yet.

last version (v67), happen randomly in orbit or not, the error : cant pick up this item reason : false(not sure)

**Comment by EtherealEmil** [comment] 2024-11-02 19:41
Alright, were you able to reproduce this issue with only my mod and its dependencies? And you mention frame drops but your frames drop when doing what? If you mean the frames drop during the grab issue you've mentioned that is just the error spam causing the frames to drop.

**Comment by EtherealEmil** [comment] 2024-11-18 22:08
May be fixed in the new version, I haven't experienced this and have no idea if this is caused by this mod so I can't/won't pursue this.

**Closed by EtherealEmil** 2024-11-18 22:08 UTC
Labels: Bug, Needs More Info
