### ISSUE TITLE
bandages/medical kit not working after some time

### ISSUE THREAD

**Issue by pizzalover99** [EtherealEmil/UsualScrap#35] opened 2024-08-29 21:18 UTC
hello again, ive noticed that the medical kit and bandages stop being usable after for example staying too long on the moon or restarting the game they just stop working which is kinda frustrating which got me killed sometimes thinking my medkit is available in my cruiser just for it not to work, maybe you can look into this, thank you again, also candy dispenser somehow isnt doing 2 damage?

**Comment by EtherealEmil** [comment] 2024-08-29 23:41
So, I was testing something with the candy dispenser and forgot to revert it before the update so that will be fixed next update. Now, this bug with the medical kit and bandages has been eluding me since I added those items and I hadn't known how to reproduce it until you wrote this post, thank you. With that said, I've squash the bug and the fix will also roll out with the next update.

**Comment by pizzalover99** [comment] 2024-08-30 00:54
thank you for your hard work

**Comment by EtherealEmil** [comment] 2024-09-01 08:04
This has been added, thank you for waiting. I will close this issue now.

**Closed by EtherealEmil** 2024-09-01 08:04 UTC
Labels: Bug, Done & Pending
